### ISSUE TITLE
purple task does not show greyed-out persian texts correctly

### ISSUE THREAD

**Issue by Master811129** [mivoligo/purple_task#18]
purple task does not show UTF-8 greyed-out texts correctly

![Screenshot_20201202_184040](https://user-images.githubusercontent.com/37829730/100893403-93a77800-34d0-11eb-8bff-4d9d1aeae405.png)
![Screenshot_20201202_184059](https://user-images.githubusercontent.com/37829730/100893416-9904c280-34d0-11eb-8a30-304ca60f3561.png)
![Screenshot_20201202_184134](https://user-images.githubusercontent.com/37829730/100893428-9d30e000-34d0-11eb-9ecf-84327b60c469.png)

**Comment by mivoligo** [comment]
@Master811129 Thanks for spotting this issue.
I think the problem here is because when the task is marked as complete, the text (task name) is crossed out. 
I'll try to find out if it's a bug in Flutter or only in my app.

**Comment by mivoligo** [comment]
Hi @Master811129 Sorry it took so long but finally I managed to find some time to work on this. Turns out the issue was font weight. For some reason Flutter doesn't render properly fonts for specific language with weight set to less than 400. 
The fix should be released soon (in hours). Version in info menu should be 1.2.1. If you can check and let me know if it fixes the bug for you, please let me know.

**Comment by Master811129** [comment]
> Hi @Master811129 Sorry it took so long but finally I managed to find some time to work on this. Turns out the issue was font weight. For some reason Flutter doesn't render properly fonts for specific language with weight set to less than 400.
> The fix should be released soon (in hours). Version in info menu should be 1.2.1. If you can check and let me know if it fixes the bug for you, please let me know.

It is working perfectly

Sepas  (means "Thank you" in persian)
I'm going to close this issue.

**Comment by mivoligo** [comment]
@Master811129 Many thanks for checking!
